# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.dropbox_client:
        class: Spatie\Dropbox\Client
        arguments:
            - "MdVJIHeo5vQAAAAAAAAHbDgnz9UKh1E6XsvNOy1_5Hzy8UbBCpMJesZY79sZ2qPI"
