vich_uploader:
    db_driver: orm
    storage:   flysystem

    mappings:
        solution_image:
            uri_prefix:         /images/solutions
            upload_destination: my_filesystem
            delete_on_update:   true
            delete_on_remove:   true
