vich_uploader:
    db_driver: orm
    mappings:
        files:
            uri_prefix:         /files
            upload_destination: '%kernel.root_dir%/../web/files'
            delete_on_update:   true
            delete_on_remove:   true
