services:
    app.twig.admin_menu_extension:
            class: AppBundle\Twig\AdminMenuExtension
            arguments:
                - '@knp_menu.helper'
                - '@knp_menu.matcher'
            tags:
                - { name: twig.extension }
    app.menu_builder:
            class: AppBundle\Menu\Builder
            arguments:
                - '@knp_menu.factory'
                - '@request_stack'
            tags:
                - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
    app.service.singleton:
            class: AppBundle\Service\Singleton
            factory: ['AppBundle\Service\Singleton', getInstance]
